from rest_framework import permissions, viewsets

from djangorestframework_fsm.viewset_mixins import get_drf_fsm_mixin

from jobapplication.models import Company, JobReference, JobApplication
from jobapplication.serializers import (CompanySerializer,
                                        JobReferenceSerializer,
                                        JobApplicationSerializer,
                                        )

DRF_FSM_MIXIN = get_drf_fsm_mixin(JobApplication, fieldname='status')


class CompanyViewset(viewsets.ModelViewSet):
    """Viewset for Company objects.

    Company views should only be accessible by authenticated users

    Fields:
        queryset: list of companies ordered by name
        serializer_class: serializer to use to represent companies
        permission_classes: restrictions on who can access company endpoints

    """

    queryset = Company.objects.all().order_by('name', )
    serializer_class = CompanySerializer
    permission_classes = (permissions.IsAuthenticated,)

    def perform_create(self, serializer):
        """
        Add currently authenticated user as creator of this company object
        :param serializer: Serializer generated using the data from current
            request
        """
        serializer.save(creator=self.request.user)


class JobReferenceViewset(viewsets.ModelViewSet):
    """Viewset for JobReference objects.

    JobReference views should only be accessible by authenticated users

    Fields:
        queryset: list of job references ordered by name
        serializer_class: serializer to use to represent job references
        permission_classes: restrictions on who can accessjob reference endpoints
    """

    queryset = JobReference.objects.all().order_by('name', )
    serializer_class = JobReferenceSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def perform_create(self, serializer):
        """
       Add currently authenticated user as creator of this JobReference object
       :param serializer: Serializer generated using the data from current
           request
       """
        serializer.save(creator=self.request.user)


class JobApplicationViewset(DRF_FSM_MIXIN, viewsets.ModelViewSet):
    """Viewset for JobApplication objects.

    JobApplication views should only be accessible by authenticated users.

    Fields:
        queryset: list of job applications ordered by submission date

    Views for each transition method are automatically generated by
    get_drf_fsm_mixin.

    References:
        https://github.com/27medkamal/djangorestframework-fsm

    """

    queryset = JobApplication.objects.all().order_by('submitted_date')
    serializer_class = JobApplicationSerializer
