# Generated by Django 2.1.3 on 2018-12-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
