# Generated by Django 2.1.3 on 2018-12-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0003_auto_20181204_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
