# Generated by Django 2.1.3 on 2018-12-05 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0005_jobapplication_rejected_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='followup_date',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='offer_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='phone_screen_date',
        ),
    ]
